### ISSUE TITLE
ListView setOnItemClickListener not Responding to click

### ISSUE THREAD

**Issue by kazaky** [flavienlaurent/NotBoringActionBar#12]
in NoBoringActionBarActivity.Java   

mListView.setOnItemClickListener(new OnItemClickListener() {

```
        @Override
        public void onItemClick(AdapterView<?> parent, View view,
                int position, long id) {
            Toast.makeText(getApplicationContext(), "position" + position,
                    1000).show();

        }
    });
```

**Comment by flavienlaurent** [comment]
If you want to set a OnItemClickListener on the listview, this is the way to do it :)

**Comment by kazaky** [comment]
:)
Sorry ,  to comment again in this closed issue ,,
i have another related Bug 

this View inside the Blue Border ,, when i click on it it acts like the first Element of the ListView 
i don't won't it to be clickable 

i tried set Clickable false in XML in all this View Elements ,, but not working ,, 
i think this is related to fake ListView Header . :/    !!

![device-2014-07-13-155235](https://cloud.githubusercontent.com/assets/4202132/4198881/fc4cba9e-37fe-11e4-85ef-fcafc9222550.png)
