### ISSUE TITLE
NotBoringActionBar with webview

### ISSUE THREAD

**Issue by jeromevdl** [flavienlaurent/NotBoringActionBar#13]
Hi Flavien,

Thanks for sharing your code. I try to use it with a webview but facing a problem. There is no header view in a webview ;) I tried to add a padding but padding does not work on webviews. I tried to play with margins but i need to requestLayout and it's a bit laggy.

Any idea ? Thanks

**Comment by flavienlaurent** [comment]
Hi Jerome,

You want to replace the listview by a webview and on webview scrolls, you want to scale and translate the ActionBar icon?

**Comment by jeromevdl** [comment]
Yes. I finally achieve that by adding a padding in the html... not the best code ever but it works. I've also seen FadingActionBar library but didn't want to use it.

**Comment by flavienlaurent** [comment]
nice :+1:

**Comment by dandan518** [comment]
Hi Flavien,

```
 Thanks for sharing your code.I tried to replace the ListView  for PinnedSectionListView  but The PinnedSectionListView  always being blocked by the picture.Can you solve my problem? thanks very much.
```
