### ISSUE TITLE
Battery drainage? Pausing animation.

### ISSUE THREAD

**Issue by sp00ne** [flavienlaurent/NotBoringActionBar#19]
Hi!

I must say this is an excellent library. There is however one issue, I notice that even though the screen is turned off, the image-swapping still occurs. I was wondering how one could pause the animations without accessing the pause() / resume() animation that were newly added in a recent-ish API? (if I remember correctly? sorry for being so vague, rookie android-dev here :-) ) 

I tried calling the onAttachWindow() and onDetachWindow() in the main-activity through onResume() and onPause() respectively, by making the classes public instead of protected in your KenBurnsView.java, but alas... no success.

**Comment by flavienlaurent** [comment]
Just block swapImage calls when the Activity onPause and release swapImage calls when the Activity onResume. You can do it with a simple boolean.

**Comment by sp00ne** [comment]
Great, so I basically added this to KenBurnsSupportView.java:

```
public void pauseAnimation() {
    mHandler.removeCallbacks(mSwapImageRunnable);
    Log.d(TAG, "**Pausing Animation");
}

public void resumeAnimation() {
    startKenBurnsAnimation();
    Log.d(TAG, "**Resuming Animation");
}
```

And called it in my MainActivity.java in the following fashion:

```
public class MainActivity extends [...] implements [...] {

    private KenBurnsSupportView mHeaderPicture;
    [...]

    @Override
    protected void onPause(){
        mHeaderPicture.pauseAnimation();
        super.onPause();
    }

    @Override
    protected void onResume(){
        mHeaderPicture.resumeAnimation();
        super.onResume();
    }
}
```

and it works like a charm! Thank you!
