### ISSUE TITLE
Image moves too far leaving the edge

### ISSUE THREAD

**Issue by inmyth** [flavienlaurent/NotBoringActionBar#8]
Sometimes the image moves too far and I can also see its edge with blank background behind it.

**Comment by AndroidDeveloperLB** [comment]
You mean that there are empty areas for the KenBurns effect?
If so, did you find a way to solve this?
I think it's related to the sizes of the bitmaps compared to the size of the view, since the calculation there doesn't look at both of them, and does everything in a random way.

**Comment by flavienlaurent** [comment]
The KenBurns effect is not the main purpose of this repo. If you want a better implementation, you can see https://github.com/flavioarfaria/KenBurnsView

**Comment by AndroidDeveloperLB** [comment]
It has the same issue, and I reported about it myself:
https://github.com/flavioarfaria/KenBurnsView/issues/4

**Comment by flavienlaurent** [comment]
ok, hope it will be fixed :)
